services:
  - type: web
    name: college-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college-db
          property: connectionString
      - key: DEBUG
        value: false 